name: streamer-analysis
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - opencv
  - ffmpeg
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - pip:
      - yt-dlp
      - mediapipe
      - deepface
      - fer
      - ffmpeg-python
